export const SKILLS = [
  "Test-Driven Development",
  "Domain-Driven Design",
  "Trunk-Based Development",
  "Extreme Programming",
  "Testing",
  "Agile Methodologies",
  "Clean Code",
  "Design Patterns",
  "Microservices",
  "Event-Driven Architecture",
  "Cloud Computing",
  "AWS",
  "JavaScript",
  "TypeScript",
  "React",
  "Tailwind CSS",
  "Git",
  "Node.js",
  "SQL/NoSQL",
  "Docker",
];
